package com.inventory.inventorymanager.model;

import jakarta.persistence.*;

import java.time.LocalDate;

/**
 * Represents a product in the inventory system.
 * Requirement 7: Define the structure of a product with its fields.
 *
 * @author Gaetano Barreca
 * @version 1.0
 */
@Entity
@Table
public class Product {

    /**
     * Unique identifier for the product, autogenerated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long productID;

    /**
     * The name of the product.
     * This field is unique and cannot be null.
     */
    @Column(nullable = false, unique = true)
    private String productName;

    /**
     * The expiry date of the product.
     */
    private LocalDate expiryDate;

    /**
     * The time duration within which the product should be marked down.
     */
    private Integer timeDurationForMarkDown;

    /**
     * Minimum threshold for alerts when stock goes below this level.
     */
    private Integer minThreshold;

    /**
     * Maximum threshold for maintaining stock.
     */
    private Integer maxThreshold;

    /**
     * The current stock level of the product.
     */
    private Integer currentStock;

    /**
     * Default constructor, required by JPA.
     */
    public Product() {
    }

    /**
     * Full constructor, initializes all fields.
     *
     * @param productID Unique identifier for the product
     * @param productName Name of the product
     * @param expiryDate Expiry date of the product
     * @param timeDurationForMarkDown Time duration for markdown
     * @param minThreshold Minimum threshold for alerts
     * @param maxThreshold Maximum threshold for stock
     * @param currentStock Current stock level
     */
    public Product(Long productID, String productName, LocalDate expiryDate, Integer timeDurationForMarkDown,
                   Integer minThreshold, Integer maxThreshold, Integer currentStock) {
        this.productID = productID;
        this.productName = productName;
        this.expiryDate = expiryDate;
        this.timeDurationForMarkDown = timeDurationForMarkDown;
        this.minThreshold = minThreshold;
        this.maxThreshold = maxThreshold;
        this.currentStock = currentStock;
    }

    // Getter and Setter methods

    public Long getProductID() {
        return productID;
    }

    public void setProductID(Long productID) {
        this.productID = productID;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public LocalDate getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(LocalDate expiryDate) {
        this.expiryDate = expiryDate;
    }

    public Integer getTimeDurationForMarkDown() {
        return timeDurationForMarkDown;
    }

    public void setTimeDurationForMarkDown(Integer timeDurationForMarkDown) {
        this.timeDurationForMarkDown = timeDurationForMarkDown;
    }

    public Integer getMinThreshold() {
        return minThreshold;
    }

    public void setMinThreshold(Integer minThreshold) {
        this.minThreshold = minThreshold;
    }

    public Integer getMaxThreshold() {
        return maxThreshold;
    }

    public void setMaxThreshold(Integer maxThreshold) {
        this.maxThreshold = maxThreshold;
    }

    public Integer getCurrentStock() {
        return currentStock;
    }

    public void setCurrentStock(Integer currentStock) {
        this.currentStock = currentStock;
    }

    @Override
    public String toString() {
        return "Product{" +
                "productID='" + productID + '\'' +
                ", productName='" + productName + '\'' +
                ", expiryDate=" + expiryDate +
                ", timeDurationForMarkDown=" + timeDurationForMarkDown +
                ", minThreshold=" + minThreshold +
                ", maxThreshold=" + maxThreshold +
                ", currentStock=" + currentStock +
                '}';
    }
}
