name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger this workflow on push to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build and Test
      run: ./mvnw clean install
